### ISSUE TITLE
TypeError: object is not a function

### ISSUE THREAD

**Issue by michaelryancaputo** [seeden/mongoose-permalink#2]
Hi there, i'm using the example that you've provided to ass the permalink plugin to my schema, however I am getting "TypeError: object is not a function" error.

```
'use strict';

var mongoose = require('mongoose');
var mongoosePages = require('mongoose-pages');
var permalink = require('mongoose-permalink');
var Schema = mongoose.Schema;

var ChannelsSchema = new Schema({
  title: {type: String},
  image: {type: String},
  brief: {type: String}
});

mongoosePages.skip(ChannelsSchema);

ChannelsSchema.plugin(permalink, {
  sources: ['title']
});

mongoose.model('Channels', ChannelsSchema);
```

**Comment by seeden** [comment]
Can you be more specific ? I really appreciate the stacktrace

**Comment by xtuc** [comment]
Hi,

I have the same error. In my case, `"mongoose": "~3.8",  "mongoose-findorcreate": "^0.1.2"`

My stacktrace:
`var NewCircle = new circle();
                                                ^
TypeError: object is not a function
    at Promise.<anonymous> (/home/sven/Web/*/*/app/API/account/circle.js:23:21)
    at Promise.<anonymous> (/home/sven/Web/*/*/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at Promise.emit (events.js:95:17)
    at Promise.emit (/home/sven/Web/*/*/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (/home/sven/Web/*/*/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
    at Object.cb (/home/sven/Web/*/*/node_modules/mongoose/lib/query.js:1153:30)
    at Object._onImmediate (/home/sven/Web/*/*/node_modules/mongoose/node_modules/mquery/lib/utils.js:137:16)
    at processImmediate [as _immediateCallback] (timers.js:354:15)`

**Comment by xtuc** [comment]
I've found my error. I overrided my circle object....
@michaelryancaputo I think you have done the same mistake. If you are using a findOne function care that you'r not overriding your Mongoose model.
